#! /bin/bash

# Iterate over the markdown files
for file in archive/*.md; do
  # Get the filename without the extension
  filename=$(basename "$file" .md)
  python3 scripts/mjml_generator.py "$file" >> "www/newsletter/$filename.mjml"
  node_modules/.bin/mjml "www/newsletter/$filename.mjml" > "www/newsletter/$filename.html"
  rm "www/newsletter/$filename.mjml"
done

# Build index.html
python3 scripts/index_generator.py > "www/newsletter/index.html"
