name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.1
      
    - name: Install Python Dependencies
      run: pip3 install markdown
      
    - name: Install Node Dependencies
      run: npm install -g mjml
      
    - name: Build
      run: make
